/*
-- Query: SELECT * FROM wineberry.Comuna
LIMIT 0, 1000

-- Date: 2013-10-06 23:26
*/
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (1,'Las Condes','13114',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (2,'Puerto Montt','10101',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (3,'Chonchi','10203',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (4,'Punta Arenas','12101',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (5,'Laguna Blanca','12102',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (6,'RÃ­o Verde','12103',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (7,'San Gregorio','12104',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (8,'Cabo de Hornos','12201',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (9,'AntÃ¡rtica','12202',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (10,'Porvenir','12301',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (11,'Primavera','12302',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (12,'Timaukel','12303',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (13,'Natales','12401',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (14,'Torres del Paine','12402',1,12);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (15,'Arica','15101',1,15);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (18,'Camarones','15102',1,15);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (19,'Putre','15201',1,15);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (20,'General Lagos','15202',1,15);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (21,'Iquique','01101',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (22,'Alto Hospicio','01102',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (23,'Pozo Almonte','01401',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (24,'CamiÃ±a','01402',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (25,'Colchane','01403',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (26,'Huara','01404',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (27,'Pica','01405',1,1);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (28,'Antofagasta','02101',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (29,'Mejillones','02102',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (30,'Sierra Gorda','02103',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (31,'Taltal','02104',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (32,'Calama','02201',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (33,'OllagÃ¼e','02202',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (34,'San Pedro de Atacama','02203',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (35,'Tocopilla','02301',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (36,'MarÃ­a Elena','02302',1,2);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (37,'CopiapÃ³','03101',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (38,'Caldera','03102',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (39,'Tierra Amarilla','03103',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (41,'ChaÃ±aral','03201',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (42,'Diego de Almagro','03202',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (43,'Vallenar','03301',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (44,'Alto del Carmen','03302',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (45,'Freirina','03303',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (46,'Huasco','03304',1,3);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (47,'La Serena','04101',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (48,'Coquimbo','04102',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (49,'Andacollo','04103',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (50,'La Higuera','04104',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (51,'Paiguano','04105',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (52,'VicuÃ±a','04106',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (53,'Illapel','04201',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (54,'Canela','04202',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (55,'Los Vilos','04203',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (56,'Salamanca','04204',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (57,'Ovalle','04301',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (58,'CombarbalÃ¡','04302',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (59,'Monte Patria','04303',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (60,'Punitaqui','04304',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (61,'RÃ­o Hurtado','04305',1,4);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (62,'ValparaÃ­so','05101',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (63,'Casablanca','05102',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (64,'ConcÃ³n','05103',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (65,'Juan FernÃ¡ndez','05104',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (66,'PuchuncavÃ­','05105',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (67,'Quintero','05107',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (68,'ViÃ±a del Mar','05109',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (69,'Isla de Pascua','05201',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (70,'Los Andes','05301',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (71,'Calle Larga','05302',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (72,'Rinconada','05303',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (73,'San Esteban','05304',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (74,'La Ligua','05401',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (75,'Cabildo','05402',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (76,'Papudo','05403',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (77,'Petorca','05404',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (78,'Zapallar','05405',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (79,'Quillota','05501',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (80,'Calera','05502',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (81,'Hijuelas','05503',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (82,'La Cruz','05504',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (83,'Nogales','05506',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (84,'San Antonio','05601',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (85,'Algarrobo','05602',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (86,'Cartagena','05603',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (87,'El Quisco','05604',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (88,'El Tabo','05605',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (89,'Santo Domingo','05606',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (90,'San Felipe','05701',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (91,'Catemu','05702',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (92,'Llaillay','05703',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (93,'Panquehue','05704',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (94,'Putaendo','05705',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (95,'Santa MarÃ­a','05706',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (96,'QuilpuÃ©','05801',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (97,'Limache','05802',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (98,'OlmuÃ©','05803',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (99,'Villa Alemana','05804',1,5);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (100,'Rancagua','06101',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (101,'Codegua','06102',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (102,'Coinco','06103',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (103,'Coltauco','06104',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (104,'DoÃ±ihue','06105',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (105,'Graneros','06106',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (106,'Las Cabras','06107',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (107,'MachalÃ­','06108',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (108,'Malloa','06109',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (109,'Mostazal','06110',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (110,'Olivar','06111',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (111,'Peumo','06112',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (112,'Pichidegua','06113',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (113,'Quinta de Tilcoco','06114',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (114,'Rengo','06115',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (115,'RequÃ­noa','06116',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (116,'San Vicente','06117',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (117,'Pichilemu','06201',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (118,'La Estrella','06202',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (119,'Litueche','06203',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (120,'Marchihue','06204',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (121,'Navidad','06205',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (122,'Paredones','06206',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (123,'San Fernando','06301',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (124,'ChÃ©pica','06302',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (125,'Chimbarongo','06303',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (126,'Lolol','06304',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (127,'Nancagua','06305',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (128,'Palmilla','06306',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (129,'Peralillo','06307',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (130,'Placilla','06308',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (131,'Pumanque','06309',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (132,'Santa Cruz','06310',1,6);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (133,'Talca','07101',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (134,'ConstituciÃ³n','07102',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (135,'Curepto','07103',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (136,'Empedrado','07104',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (137,'Maule','07105',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (138,'Pelarco','07106',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (139,'Pencahue','07107',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (140,'RÃ­o Claro','07108',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (141,'San Clemente','07109',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (142,'San Rafael','07110',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (143,'Cauquenes','07201',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (144,'Chanco','07202',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (145,'Pelluhue','07203',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (146,'CuricÃ³','07301',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (147,'HualaÃ±Ã©','07302',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (148,'LicantÃ©n','07303',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (149,'Molina','07304',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (150,'Rauco','07305',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (151,'Romeral','07306',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (152,'Sagrada Familia','07307',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (153,'Teno','07308',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (154,'VichuquÃ©n','07309',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (155,'Linares','07401',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (156,'ColbÃºn','07402',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (157,'LongavÃ­','07403',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (158,'Parral','07404',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (159,'Retiro','07405',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (160,'San Javier','07406',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (161,'Villa Alegre','07407',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (162,'Yerbas Buenas','07408',1,7);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (163,'ConcepciÃ³n','08101',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (164,'Coronel','08102',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (165,'Chiguayante','08103',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (166,'Florida','08104',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (167,'Hualqui','08105',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (168,'Lota','08106',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (169,'Penco','08107',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (170,'San Pedro de la Paz','08108',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (171,'Santa Juana','08109',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (172,'Talcahuano','08110',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (173,'TomÃ©','08111',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (174,'HualpÃ©n','08112',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (175,'Lebu','08201',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (176,'Arauco','08202',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (177,'CaÃ±ete','08203',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (178,'Contulmo','08204',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (179,'Curanilahue','08205',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (180,'Los Ãlamos','08206',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (181,'TirÃºa','08207',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (182,'Los Ãngeles','08301',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (183,'Antuco','08302',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (184,'Cabrero','08303',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (185,'Laja','08304',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (186,'MulchÃ©n','08305',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (187,'Nacimiento','08306',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (188,'Negrete','08307',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (189,'Quilaco','08309',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (190,'Quilleco','08309',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (191,'San Rosendo','08310',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (192,'Santa BÃ¡rbara','08311',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (193,'Tucapel','08312',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (194,'Yumbel','08313',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (195,'Alto BiobÃ­o','08314',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (196,'ChillÃ¡n','08401',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (197,'Bulnes','08402',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (198,'Cobquecura','08403',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (199,'Coelemu','08404',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (200,'Coihueco','08405',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (201,'ChillÃ¡n Viejo','08406',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (202,'El Carmen','08407',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (203,'Ninhue','08408',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (204,'Ã‘iquÃ©n','08409',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (205,'Pemuco','08410',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (206,'Pinto','08411',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (207,'Portezuelo','08412',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (208,'QuillÃ³n','08413',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (209,'Quirihue','08414',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (210,'RÃ¡nquil','08415',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (211,'San Carlos','08416',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (212,'San FabiÃ¡n','08417',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (213,'San Ignacio','08418',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (214,'San NicolÃ¡s','08419',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (215,'Treguaco','08420',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (216,'Yungay','08421',1,8);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (217,'Temuco','09101',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (218,'Carahue','09102',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (219,'Cunco','09103',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (220,'Curarrehue','09104',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (221,'Freire','09105',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (222,'Galvarino','09106',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (223,'Gorbea','09107',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (224,'Lautaro','09108',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (225,'Loncoche','09109',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (226,'Melipeuco','09110',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (227,'Nueva Imperial','09111',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (228,'Padre las Casas','09112',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (229,'Perquenco','09113',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (230,'PitrufquÃ©n','09114',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (231,'PucÃ³n','09115',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (232,'Saavedra','09116',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (233,'Teodoro Schmidt','09117',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (234,'ToltÃ©n','09118',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (235,'VilcÃºn','09119',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (236,'Villarrica','09120',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (237,'Cholchol','09121',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (238,'Angol','09201',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (239,'Collipulli','09202',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (240,'CuracautÃ­n','09203',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (241,'Ercilla','09204',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (242,'Lonquimay','09205',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (243,'Los Sauces','09206',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (244,'Lumaco','09207',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (245,'PurÃ©n','09208',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (246,'Renaico','09209',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (247,'TraiguÃ©n','09210',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (248,'Victoria','09211',1,9);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (249,'Valdivia','14101',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (250,'Corral','14102',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (251,'Lanco','14103',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (252,'Los Lagos','14104',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (253,'MÃ¡fil','14105',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (254,'Mariquina','14106',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (255,'Paillaco','14107',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (256,'Panguipulli','14108',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (257,'La UniÃ³n','14201',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (258,'Futrono','14202',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (259,'Lago Ranco','14203',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (260,'RÃ­o Bueno','14204',1,14);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (261,'Calbuco','10102',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (262,'CochamÃ³','10103',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (263,'Fresia','10104',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (264,'Frutillar','10105',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (265,'Los Muermos','10106',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (266,'Llanquihue','10107',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (267,'MaullÃ­n','10108',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (268,'Puerto Varas','10109',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (269,'Castro','10201',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (270,'Ancud','10202',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (271,'Curaco de VÃ©lez','10204',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (272,'Dalcahue','10205',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (273,'PuqueldÃ³n','10206',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (274,'QueilÃ©n','10207',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (275,'QuellÃ³n','10208',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (276,'Quemchi','10209',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (277,'Quinchao','10210',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (278,'Osorno','10301',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (279,'Puerto Octay','10302',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (280,'Purranque','10303',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (281,'Puyehue','10304',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (282,'RÃ­o Negro','10305',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (283,'San Juan de la Costa','10306',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (284,'San Pablo','10307',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (285,'ChaitÃ©n','10401',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (286,'FutaleufÃº','10402',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (287,'HualaihuÃ©','10403',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (288,'Palena','10404',1,10);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (289,'Coihaique','11101',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (290,'Lago Verde','11102',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (291,'AisÃ©n','11201',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (292,'Cisnes','11202',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (293,'Guaitecas','11203',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (294,'Cochrane','11301',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (295,'O\'Higgins','11302',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (296,'Tortel','11303',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (297,'Chile Chico','11401',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (298,'RÃ­o IbÃ¡Ã±ez','11402',1,11);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (299,'Santiago','13101',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (300,'Cerrillos','13102',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (301,'Cerro Navia','13103',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (302,'ConchalÃ­','13104',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (303,'El Bosque','13105',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (304,'EstaciÃ³n Central','13106',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (305,'Huechuraba','13107',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (306,'Independencia','13108',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (307,'La Cisterna','13109',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (308,'La Florida','13110',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (309,'La Granja','13111',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (310,'La Pintana','13112',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (311,'La Reina','13113',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (312,'Lo Barnechea','13115',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (313,'Lo Espejo','13116',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (314,'Lo Prado','13117',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (315,'Macul','13118',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (316,'MaipÃº','13119',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (317,'Ã‘uÃ±oa','13120',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (318,'Pedro Aguirre Cerda','13121',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (319,'PeÃ±alolÃ©n','13122',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (320,'Providencia','13123',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (321,'Pudahuel','13124',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (322,'Quilicura','13125',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (323,'Quinta Normal','13126',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (324,'Recoleta','13127',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (325,'Renca','13128',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (326,'San JoaquÃ­n','13129',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (327,'San Miguel','13130',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (328,'San RamÃ³n','13131',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (329,'Vitacura','13132',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (330,'Puente Alto','13201',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (331,'Pirque','13202',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (332,'San JosÃ© de Maipo','13203',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (333,'Colina','13301',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (334,'Lampa','13302',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (335,'Tiltil','13303',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (336,'San Bernardo','13401',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (337,'Buin','13402',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (338,'Calera de Tango','13403',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (339,'Paine','13404',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (340,'Melipilla','13501',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (341,'AlhuÃ©','13502',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (342,'CuracavÃ­','13503',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (343,'MarÃ­a Pinto','13504',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (344,'San Pedro','13505',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (345,'Talagante','13601',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (346,'El Monte','13602',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (347,'Isla de Maipo','13603',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (348,'Padre Hurtado','13604',1,13);
INSERT INTO `Comuna` (`idComuna`,`nombreComuna`,`codeComuna`,`activoComuna`,`Region_idRegion`) VALUES (349,'PeÃ±aflor','13605',1,13);
