/*
-- Query: SELECT * FROM wineberry.Pagina
LIMIT 0, 1000

-- Date: 2014-01-09 09:55
*/
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (1,'index.php','index.php','Inicio (MenÃº Superior)',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (2,'informes.php','informes.php','Informes (MenÃº Superior)',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (3,'admin.php','admin.php','AdministraciÃ³n (MenÃº Superior)',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (4,'login.php','login.php','Login (MenÃº Superior)',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (5,'#usr_mod','pages_admin/usr_mod.php','Lista de Usuarios',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (6,'#roles_mod','pages_admin/roles_mod.php','Lista de Roles',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (7,'#roles_perm_mod','pages_admin/roles_perm_mod.php','Permisos por rol',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (8,'#cto_tipo_mod','pages_admin/cto_tipo_mod.php','Lista de Tipos de contacto',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (9,'#mat_mod','pages_admin/mat_mod.php','Lista de Materias',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (10,'#mat_tipo_mod','pages_admin/mat_tipo_mod.php','Lista de Tipos de materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (11,'#mat_tar_mod','pages_admin/mat_tar_mod.php','Lista de Tarifas por materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (12,'#fact_estdo_mod','pages_admin/fact_estdo_mod.php','Lista de Estados de factura',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (13,'#mon_mod','pages_admin/mon_mod.php','Lista de Tipos de moneda',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (14,'#tipo_abono_mod','pages_admin/tipo_abono_mod.php','Lista de Tipos de abono',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (15,'#tipo_gasto_mod','pages_admin/tipo_gasto_mod.php','Lista de Tipos de gasto',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (16,'#feriados_mod','pages_admin/feriados_mod.php','Lista de Feriados legales',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (17,'#pais_mod','pages_admin/pais_mod.php','Lista de PaÃ­ses',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (18,'#region_mod','pages_admin/region_mod.php','Lista de Regiones',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (19,'#comuna_mod','pages_admin/comuna_mod.php','Lista de Comunas',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (20,'#label_mod','pages_admin/label_mod.php','Lista de Labels',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (21,'#menu_mod','pages_admin/menu_mod.php','Lista de Items de menÃº',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (22,'#paginas_mod','pages_admin/paginas_mod.php','Lista de PÃ¡ginas del sistema',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (23,'#param_mod','pages_admin/param_mod.php','Lista de ParÃ¡metros globales',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (24,'#version','pages_admin/version.php','VersiÃ³n del sistema',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (25,'#licencia','pages_admin/licencia.php','Licencia (EULA)',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (26,'act_desact.php','pages_admin/act_desact.php','Activar o desactivar registro de una grilla',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (27,'comuna_crear.php','pages_admin/comuna_crear.php','CreaciÃ³n de Comuna',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (28,'comuna_editar.php','pages_admin/comuna_editar.php','EdiciÃ³n de Comuna',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (29,'cto_tipo_crear.php','pages_admin/cto_tipo_crear.php','CreaciÃ³n de Tipo contacto',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (30,'cto_tipo_editar.php','pages_admin/cto_tipo_editar.php','EdiciÃ³n de Tipo contacto',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (31,'fact_estdo_crear.php','pages_admin/fact_estdo_crear.php','CreaciÃ³n de Estados factura',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (32,'fact_estdo_editar.php','pages_admin/fact_estdo_editar.php','EdiciÃ³n de Estados factura',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (33,'feriados_crear.php','pages_admin/feriados_crear.php','CreaciÃ³n de Feriado legal',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (34,'feriados_editar.php','pages_admin/feriados_editar.php','EdiciÃ³n de Feriado legal',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (35,'label_crear.php','pages_admin/label_crear.php','CreaciÃ³n de Label',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (36,'label_editar.php','pages_admin/label_editar.php','EdiciÃ³n de Label',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (37,'mat_crear.php','pages_admin/mat_crear.php','CreaciÃ³n de Materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (38,'mat_editar.php','pages_admin/mat_editar.php','EdiciÃ³n de Materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (39,'mat_tar_crear.php','pages_admin/mat_tar_crear.php','CreaciÃ³n de Tarifa por materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (40,'mat_tar_editar.php','pages_admin/mat_tar_editar.php','EdiciÃ³n de Tarifa por materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (41,'mat_tipo_crear.php','pages_admin/mat_tipo_crear.php','CreaciÃ³n de Tipo de materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (42,'mat_tipo_editar.php','pages_admin/mat_tipo_editar.php','EdiciÃ³n de Tipo de materia',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (43,'menu_crear.php','pages_admin/menu_crear.php','CreaciÃ³n Item de menÃº',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (44,'menu_editar.php','pages_admin/menu_editar.php','EdiciÃ³n Item de menÃº',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (45,'mon_crear.php','pages_admin/mon_crear.php','CreaciÃ³n de Tipo de moneda',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (46,'mon_editar.php','pages_admin/mon_editar.php','EdiciÃ³n de Tipo de moneda',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (47,'paginas_crear.php','pages_admin/paginas_crear.php','CreaciÃ³n de PÃ¡gina del sistema',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (48,'paginas_editar.php','pages_admin/paginas_editar.php','EdiciÃ³n de PÃ¡gina del sistema',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (49,'pais_crear.php','pages_admin/pais_crear.php','CreaciÃ³n de PaÃ­s',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (50,'pais_editar.php','pages_admin/pais_editar.php','EdiciÃ³n de PaÃ­s',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (51,'param_crear.php','pages_admin/param_crear.php','CreaciÃ³n de ParÃ¡metro global',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (52,'param_editar.php','pages_admin/param_editar.php','EdiciÃ³n de ParÃ¡metro Global',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (53,'region_crear.php','pages_admin/region_crear.php','CreaciÃ³n de RegiÃ³n',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (54,'region_editar.php','pages_admin/region_editar.php','EdiciÃ³n de RegiÃ³n',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (55,'roles_crear.php','pages_admin/roles_crear.php','CreaciÃ³n de Rol',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (56,'roles_editar.php','pages_admin/roles_editar.php','EdiciÃ³n de Rol',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (57,'tipo_abono_crear.php','pages_admin/tipo_abono_crear.php','CreaciÃ³n de Tipo de abono',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (58,'tipo_abono_editar.php','pages_admin/tipo_abono_editar.php','EdiciÃ³n de Tipo de abono',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (59,'tipo_gasto_crear.php','pages_admin/tipo_gasto_crear.php','CreaciÃ³n de Tipo de gasto',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (60,'tipo_gasto_editar.php','pages_admin/tipo_gasto_editar.php','EdiciÃ³n de Tipo de gasto',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (61,'usr_clave_mod.php','pages_admin/usr_clave_mod.php','ModificaciÃ³n de clave',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (62,'usr_crear.php','pages_admin/usr_crear.php','CreaciÃ³n de Usuario',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (63,'usr_editar.php','pages_admin/usr_editar.php','EdiciÃ³n de Usuario',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (64,'usr_mi_perfil.php','pages_admin/usr_mi_perfil.php','EdiciÃ³n de Perfil del usuario',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (65,'usr_tar_mod.php','pages_admin/usr_tar_mod.php','EdiciÃ³n de Tarifa del usuario',1);
INSERT INTO `Pagina` (`idPagina`,`urlPagina`,`nombrePagina`,`descripcionPagina`,`activoPagina`) VALUES (66,'#paginas_paginas_mod','pages_admin/paginas_paginas_mod.php','Relaciones entre pÃ¡ginas del sistema',1);
