-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 23:31:00 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wineberry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wineberry` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `wineberry` ;

-- -----------------------------------------------------
-- Table `wineberry`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wineberry`.`Device` ;

CREATE TABLE IF NOT EXISTS `wineberry`.`Device` (
  `idDevice` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Tabla de dispositivos',
  `nombreDevice` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `codigoDevice` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `posicionDevice` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `descripcionDevice` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idDevice`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `wineberry`.`Data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wineberry`.`Data` ;

CREATE TABLE IF NOT EXISTS `wineberry`.`Data` (
  `idData` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `infoData` DOUBLE NOT NULL,
  `Device_idDevice` INT(10) UNSIGNED NOT NULL,
  `timeData` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idData`),
  UNIQUE INDEX `timeData_UNIQUE` (`timeData` ASC),
  INDEX `fk_Data_Device1_idx` (`Device_idDevice` ASC),
  CONSTRAINT `fk_Data_Device1`
    FOREIGN KEY (`Device_idDevice`)
    REFERENCES `wineberry`.`Device` (`idDevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `wineberry`.`Raspberry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wineberry`.`Raspberry` ;

CREATE TABLE IF NOT EXISTS `wineberry`.`Raspberry` (
  `idRaspberry` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreRaspberry` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `serieRaspberry` VARCHAR(17) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `posicionRaspberry` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `descripcionRaspberry` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL COMMENT 'Tabla de identificación de las Raspberry',
  PRIMARY KEY (`idRaspberry`),
  UNIQUE INDEX `nombreRaspberry_UNIQUE` (`nombreRaspberry` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `wineberry`.`DeviceXRaspberry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wineberry`.`DeviceXRaspberry` ;

CREATE TABLE IF NOT EXISTS `wineberry`.`DeviceXRaspberry` (
  `Raspberry_idRaspberry` INT(10) UNSIGNED NOT NULL,
  `Device_idDevice` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_table1_Raspberry1_idx` (`Raspberry_idRaspberry` ASC),
  INDEX `fk_table1_Device1_idx` (`Device_idDevice` ASC),
  CONSTRAINT `fk_table1_Device1`
    FOREIGN KEY (`Device_idDevice`)
    REFERENCES `wineberry`.`Device` (`idDevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Raspberry1`
    FOREIGN KEY (`Raspberry_idRaspberry`)
    REFERENCES `wineberry`.`Raspberry` (`idRaspberry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `wineberry`.`Raw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wineberry`.`Raw` ;

CREATE TABLE IF NOT EXISTS `wineberry`.`Raw` (
  `idRaw` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `inserttimeRaw` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `dataRaw` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`idRaw`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
